class Widget {
  
  int cx, cy, tx, ty, lx, ly, rx, ry;
  
  Widget (int cx, int cy) {
    this.cx = cx;
    this.cy = cy;
    this.tx = cx;
    this.ty = cy - 4;
    this.lx = cx - 4;
    this.ly = cy + 2;
    this.rx = cx + 4;
    this.ry = cy + 2;
  }
  
  void display() {
    fill(this.getTopColor());
    this.displayTop();
//    rect(50, 50, 50, 50);
    fill(this.getLeftColor());
    this.displayLeft();
    fill(this.getRightColor());
    this.displayRight();
  }
  
  private color getTopColor() {
    float totalR, avgR, totalG, avgG, totalB, avgB;
  totalR = red(get(tx - 5, ty - 2));
  totalR = totalR + red(get(tx - 4, ty - 2));
  totalR = totalR + red(get(tx - 3, ty - 2));
  totalR = totalR + red(get(tx + 3, ty - 2));
  totalR = totalR + red(get(tx + 4, ty - 2));
  totalR = totalR + red(get(tx + 5, ty - 2));
  totalR = totalR + red(get(tx - 7, ty - 1));
  totalR = totalR + red(get(tx - 6, ty - 1));
  totalR = totalR + red(get(tx - 5, ty - 1));
  totalR = totalR + red(get(tx - 4, ty - 1));
  totalR = totalR + red(get(tx - 3, ty - 1));
  totalR = totalR + red(get(tx - 2, ty - 1));
  totalR = totalR + red(get(tx - 1, ty - 1));
  totalR = totalR + red(get(tx + 1, ty - 1));
  totalR = totalR + red(get(tx + 2, ty - 1));
  totalR = totalR + red(get(tx + 3, ty - 1));
  totalR = totalR + red(get(tx + 4, ty - 1));
  totalR = totalR + red(get(tx + 5, ty - 1));
  totalR = totalR + red(get(tx + 6, ty - 1));
  totalR = totalR + red(get(tx + 7, ty - 1));
  totalR = totalR + red(get(tx - 8, ty));
  totalR = totalR + red(get(tx - 7, ty));
  totalR = totalR + red(get(tx - 6, ty));
  totalR = totalR + red(get(tx - 5, ty));
  totalR = totalR + red(get(tx - 4, ty));
  totalR = totalR + red(get(tx - 3, ty));
  totalR = totalR + red(get(tx - 2, ty));
  totalR = totalR + red(get(tx - 1, ty));
  totalR = totalR + red(get(tx, ty));
  totalR = totalR + red(get(tx + 1, ty));
  totalR = totalR + red(get(tx + 2, ty));
  totalR = totalR + red(get(tx + 3, ty));
  totalR = totalR + red(get(tx + 4, ty));
  totalR = totalR + red(get(tx + 5, ty));
  totalR = totalR + red(get(tx + 6, ty));
  totalR = totalR + red(get(tx + 7, ty));
  totalR = totalR + red(get(tx + 8, ty));
  totalR = totalR + red(get(tx - 6, ty + 1));
  totalR = totalR + red(get(tx - 5, ty + 1));
  totalR = totalR + red(get(tx - 4, ty + 1));
  totalR = totalR + red(get(tx - 3, ty + 1));
  totalR = totalR + red(get(tx - 2, ty + 1));
  totalR = totalR + red(get(tx - 1, ty + 1));
  totalR = totalR + red(get(tx, ty + 1));
  totalR = totalR + red(get(tx + 1, ty + 1));
  totalR = totalR + red(get(tx + 2, ty + 1));
  totalR = totalR + red(get(tx + 3, ty + 1));
  totalR = totalR + red(get(tx + 4, ty + 1));
  totalR = totalR + red(get(tx + 5, ty + 1));
  totalR = totalR + red(get(tx + 6, ty + 1));
  totalR = totalR + red(get(tx - 4, ty + 2));
  totalR = totalR + red(get(tx - 3, ty + 2));
  totalR = totalR + red(get(tx - 2, ty + 2));
  totalR = totalR + red(get(tx - 1, ty + 2));
  totalR = totalR + red(get(tx, ty + 2));
  totalR = totalR + red(get(tx + 1, ty + 2));
  totalR = totalR + red(get(tx + 2, ty + 2));
  totalR = totalR + red(get(tx + 3, ty + 2));
  totalR = totalR + red(get(tx + 4, ty + 2));
  totalR = totalR + red(get(tx - 2, ty + 3));
  totalR = totalR + red(get(tx - 1, ty + 3));
  totalR = totalR + red(get(tx, ty + 3));
  totalR = totalR + red(get(tx + 1, ty + 3));
  totalR = totalR + red(get(tx + 2, ty + 3));
  totalR = totalR + red(get(tx, ty + 4));
  avgR = totalR / 65;


  totalG = green(get(tx - 5, ty - 2));
  totalG = totalG + green(get(tx - 4, ty - 2));
  totalG = totalG + green(get(tx - 3, ty - 2));
  totalG = totalG + green(get(tx + 3, ty - 2));
  totalG = totalG + green(get(tx + 4, ty - 2));
  totalG = totalG + green(get(tx + 5, ty - 2));
  totalG = totalG + green(get(tx - 7, ty - 1));
  totalG = totalG + green(get(tx - 6, ty - 1));
  totalG = totalG + green(get(tx - 5, ty - 1));
  totalG = totalG + green(get(tx - 4, ty - 1));
  totalG = totalG + green(get(tx - 3, ty - 1));
  totalG = totalG + green(get(tx - 2, ty - 1));
  totalG = totalG + green(get(tx - 1, ty - 1));
  totalG = totalG + green(get(tx + 1, ty - 1));
  totalG = totalG + green(get(tx + 2, ty - 1));
  totalG = totalG + green(get(tx + 3, ty - 1));
  totalG = totalG + green(get(tx + 4, ty - 1));
  totalG = totalG + green(get(tx + 5, ty - 1));
  totalG = totalG + green(get(tx + 6, ty - 1));
  totalG = totalG + green(get(tx + 7, ty - 1));
  totalG = totalG + green(get(tx - 8, ty));
  totalG = totalG + green(get(tx - 7, ty));
  totalG = totalG + green(get(tx - 6, ty));
  totalG = totalG + green(get(tx - 5, ty));
  totalG = totalG + green(get(tx - 4, ty));
  totalG = totalG + green(get(tx - 3, ty));
  totalG = totalG + green(get(tx - 2, ty));
  totalG = totalG + green(get(tx - 1, ty));
  totalG = totalG + green(get(tx, ty));
  totalG = totalG + green(get(tx + 1, ty));
  totalG = totalG + green(get(tx + 2, ty));
  totalG = totalG + green(get(tx + 3, ty));
  totalG = totalG + green(get(tx + 4, ty));
  totalG = totalG + green(get(tx + 5, ty));
  totalG = totalG + green(get(tx + 6, ty));
  totalG = totalG + green(get(tx + 7, ty));
  totalG = totalG + green(get(tx + 8, ty));
  totalG = totalG + green(get(tx - 6, ty + 1));
  totalG = totalG + green(get(tx - 5, ty + 1));
  totalG = totalG + green(get(tx - 4, ty + 1));
  totalG = totalG + green(get(tx - 3, ty + 1));
  totalG = totalG + green(get(tx - 2, ty + 1));
  totalG = totalG + green(get(tx - 1, ty + 1));
  totalG = totalG + green(get(tx, ty + 1));
  totalG = totalG + green(get(tx + 1, ty + 1));
  totalG = totalG + green(get(tx + 2, ty + 1));
  totalG = totalG + green(get(tx + 3, ty + 1));
  totalG = totalG + green(get(tx + 4, ty + 1));
  totalG = totalG + green(get(tx + 5, ty + 1));
  totalG = totalG + green(get(tx + 6, ty + 1));
  totalG = totalG + green(get(tx - 4, ty + 2));
  totalG = totalG + green(get(tx - 3, ty + 2));
  totalG = totalG + green(get(tx - 2, ty + 2));
  totalG = totalG + green(get(tx - 1, ty + 2));
  totalG = totalG + green(get(tx, ty + 2));
  totalG = totalG + green(get(tx + 1, ty + 2));
  totalG = totalG + green(get(tx + 2, ty + 2));
  totalG = totalG + green(get(tx + 3, ty + 2));
  totalG = totalG + green(get(tx + 4, ty + 2));
  totalG = totalG + green(get(tx - 2, ty + 3));
  totalG = totalG + green(get(tx - 1, ty + 3));
  totalG = totalG + green(get(tx, ty + 3));
  totalG = totalG + green(get(tx + 1, ty + 3));
  totalG = totalG + green(get(tx + 2, ty + 3));
  totalG = totalG + green(get(tx, ty + 4));
  avgG = totalG / 65;


  totalB = blue(get(tx - 5, ty - 2));
  totalB = totalB + blue(get(tx - 4, ty - 2));
  totalB = totalB + blue(get(tx - 3, ty - 2));
  totalB = totalB + blue(get(tx + 3, ty - 2));
  totalB = totalB + blue(get(tx + 4, ty - 2));
  totalB = totalB + blue(get(tx + 5, ty - 2));
  totalB = totalB + blue(get(tx - 7, ty - 1));
  totalB = totalB + blue(get(tx - 6, ty - 1));
  totalB = totalB + blue(get(tx - 5, ty - 1));
  totalB = totalB + blue(get(tx - 4, ty - 1));
  totalB = totalB + blue(get(tx - 3, ty - 1));
  totalB = totalB + blue(get(tx - 2, ty - 1));
  totalB = totalB + blue(get(tx - 1, ty - 1));
  totalB = totalB + blue(get(tx + 1, ty - 1));
  totalB = totalB + blue(get(tx + 2, ty - 1));
  totalB = totalB + blue(get(tx + 3, ty - 1));
  totalB = totalB + blue(get(tx + 4, ty - 1));
  totalB = totalB + blue(get(tx + 5, ty - 1));
  totalB = totalB + blue(get(tx + 6, ty - 1));
  totalB = totalB + blue(get(tx + 7, ty - 1));
  totalB = totalB + blue(get(tx - 8, ty));
  totalB = totalB + blue(get(tx - 7, ty));
  totalB = totalB + blue(get(tx - 6, ty));
  totalB = totalB + blue(get(tx - 5, ty));
  totalB = totalB + blue(get(tx - 4, ty));
  totalB = totalB + blue(get(tx - 3, ty));
  totalB = totalB + blue(get(tx - 2, ty));
  totalB = totalB + blue(get(tx - 1, ty));
  totalB = totalB + blue(get(tx, ty));
  totalB = totalB + blue(get(tx + 1, ty));
  totalB = totalB + blue(get(tx + 2, ty));
  totalB = totalB + blue(get(tx + 3, ty));
  totalB = totalB + blue(get(tx + 4, ty));
  totalB = totalB + blue(get(tx + 5, ty));
  totalB = totalB + blue(get(tx + 6, ty));
  totalB = totalB + blue(get(tx + 7, ty));
  totalB = totalB + blue(get(tx + 8, ty));
  totalB = totalB + blue(get(tx - 6, ty + 1));
  totalB = totalB + blue(get(tx - 5, ty + 1));
  totalB = totalB + blue(get(tx - 4, ty + 1));
  totalB = totalB + blue(get(tx - 3, ty + 1));
  totalB = totalB + blue(get(tx - 2, ty + 1));
  totalB = totalB + blue(get(tx - 1, ty + 1));
  totalB = totalB + blue(get(tx, ty + 1));
  totalB = totalB + blue(get(tx + 1, ty + 1));
  totalB = totalB + blue(get(tx + 2, ty + 1));
  totalB = totalB + blue(get(tx + 3, ty + 1));
  totalB = totalB + blue(get(tx + 4, ty + 1));
  totalB = totalB + blue(get(tx + 5, ty + 1));
  totalB = totalB + blue(get(tx + 6, ty + 1));
  totalB = totalB + blue(get(tx - 4, ty + 2));
  totalB = totalB + blue(get(tx - 3, ty + 2));
  totalB = totalB + blue(get(tx - 2, ty + 2));
  totalB = totalB + blue(get(tx - 1, ty + 2));
  totalB = totalB + blue(get(tx, ty + 2));
  totalB = totalB + blue(get(tx + 1, ty + 2));
  totalB = totalB + blue(get(tx + 2, ty + 2));
  totalB = totalB + blue(get(tx + 3, ty + 2));
  totalB = totalB + blue(get(tx + 4, ty + 2));
  totalB = totalB + blue(get(tx - 2, ty + 3));
  totalB = totalB + blue(get(tx - 1, ty + 3));
  totalB = totalB + blue(get(tx, ty + 3));
  totalB = totalB + blue(get(tx + 1, ty + 3));
  totalB = totalB + blue(get(tx + 2, ty + 3));
  totalB = totalB + blue(get(tx, ty + 4));
  avgB = totalB / 65;
    return color(avgR, avgG, avgB);  
  }
    
  private color getLeftColor(){
      float totalR, avgR, totalG, avgG, totalB, avgB;
  totalR = red(get(lx - 4, ly - 6));
  totalR = totalR + red(get(lx - 3, ly - 6));
  totalR = totalR + red(get(lx - 4, ly - 5));
  totalR = totalR + red(get(lx - 3, ly - 5));
  totalR = totalR + red(get(lx - 2, ly - 5));
  totalR = totalR + red(get(lx - 1, ly - 5));
  totalR = totalR + red(get(lx - 4, ly - 4));
  totalR = totalR + red(get(lx - 3, ly - 4));
  totalR = totalR + red(get(lx - 2, ly - 4));
  totalR = totalR + red(get(lx - 1, ly - 4));
  totalR = totalR + red(get(lx, ly - 4));
  totalR = totalR + red(get(lx + 1, ly - 4));
  totalR = totalR + red(get(lx - 4, ly - 3));
  totalR = totalR + red(get(lx - 3, ly - 3));
  totalR = totalR + red(get(lx - 2, ly - 3));
  totalR = totalR + red(get(lx - 1, ly - 3));
  totalR = totalR + red(get(lx, ly - 3));
  totalR = totalR + red(get(lx + 1, ly - 3));
  totalR = totalR + red(get(lx + 2, ly - 3));
  totalR = totalR + red(get(lx + 3, ly - 3));
  totalR = totalR + red(get(lx - 4, ly - 2));
  totalR = totalR + red(get(lx - 3, ly - 2));
  totalR = totalR + red(get(lx - 2, ly - 2));
  totalR = totalR + red(get(lx - 1, ly - 2));
  totalR = totalR + red(get(lx, ly - 2));
  totalR = totalR + red(get(lx + 1, ly - 2));
  totalR = totalR + red(get(lx + 2, ly - 2));
  totalR = totalR + red(get(lx + 3, ly - 2));
  totalR = totalR + red(get(lx + 4, ly - 2));
  totalR = totalR + red(get(lx - 3, ly - 1));
  totalR = totalR + red(get(lx - 2, ly - 1));
  totalR = totalR + red(get(lx - 1, ly - 1));
  totalR = totalR + red(get(lx, ly - 1));
  totalR = totalR + red(get(lx + 1, ly - 1));
  totalR = totalR + red(get(lx + 2, ly - 1));
  totalR = totalR + red(get(lx + 3, ly - 1));
  totalR = totalR + red(get(lx + 4, ly - 1));
  totalR = totalR + red(get(lx - 1, ly));
  totalR = totalR + red(get(lx, ly));
  totalR = totalR + red(get(lx + 1, ly));
  totalR = totalR + red(get(lx + 2, ly));
  totalR = totalR + red(get(lx + 3, ly));
  totalR = totalR + red(get(lx + 4, ly));
  totalR = totalR + red(get(lx, ly + 1));
  totalR = totalR + red(get(lx + 1, ly + 1));
  totalR = totalR + red(get(lx + 2, ly + 1));
  totalR = totalR + red(get(lx + 3, ly + 1));
  totalR = totalR + red(get(lx + 4, ly + 1));
  totalR = totalR + red(get(lx, ly + 2));
  totalR = totalR + red(get(lx + 1, ly + 2));
  totalR = totalR + red(get(lx + 2, ly + 2));
  totalR = totalR + red(get(lx + 3, ly + 2));
  totalR = totalR + red(get(lx + 4, ly + 2));
  totalR = totalR + red(get(lx, ly + 3));
  totalR = totalR + red(get(lx + 1, ly + 3));
  totalR = totalR + red(get(lx + 2, ly + 3));
  totalR = totalR + red(get(lx + 3, ly + 3));
  totalR = totalR + red(get(lx + 4, ly + 3));
  totalR = totalR + red(get(lx, ly + 4));
  totalR = totalR + red(get(lx + 1, ly + 4));
  totalR = totalR + red(get(lx + 2, ly + 4));
  totalR = totalR + red(get(lx + 3, ly + 4));
  totalR = totalR + red(get(lx + 4, ly + 4));
  totalR = totalR + red(get(lx, ly + 5));
  totalR = totalR + red(get(lx + 1, ly + 5));
  totalR = totalR + red(get(lx + 2, ly + 5));
  totalR = totalR + red(get(lx + 3, ly + 5));
  totalR = totalR + red(get(lx + 4, ly + 5));
  totalR = totalR + red(get(lx + 1, ly + 6));
  totalR = totalR + red(get(lx + 2, ly + 6));
  totalR = totalR + red(get(lx + 3, ly + 6));
  totalR = totalR + red(get(lx + 4, ly + 6));
  totalR = totalR + red(get(lx + 3, ly + 7));
  totalR = totalR + red(get(lx + 4, ly + 7));
  avgR = totalR / 74;

  totalG = green(get(lx - 4, ly - 6));
  totalG = totalG + green(get(lx - 3, ly - 6));
  totalG = totalG + green(get(lx - 4, ly - 5));
  totalG = totalG + green(get(lx - 3, ly - 5));
  totalG = totalG + green(get(lx - 2, ly - 5));
  totalG = totalG + green(get(lx - 1, ly - 5));
  totalG = totalG + green(get(lx - 4, ly - 4));
  totalG = totalG + green(get(lx - 3, ly - 4));
  totalG = totalG + green(get(lx - 2, ly - 4));
  totalG = totalG + green(get(lx - 1, ly - 4));
  totalG = totalG + green(get(lx, ly - 4));
  totalG = totalG + green(get(lx + 1, ly - 4));
  totalG = totalG + green(get(lx - 4, ly - 3));
  totalG = totalG + green(get(lx - 3, ly - 3));
  totalG = totalG + green(get(lx - 2, ly - 3));
  totalG = totalG + green(get(lx - 1, ly - 3));
  totalG = totalG + green(get(lx, ly - 3));
  totalG = totalG + green(get(lx + 1, ly - 3));
  totalG = totalG + green(get(lx + 2, ly - 3));
  totalG = totalG + green(get(lx + 3, ly - 3));
  totalG = totalG + green(get(lx - 4, ly - 2));
  totalG = totalG + green(get(lx - 3, ly - 2));
  totalG = totalG + green(get(lx - 2, ly - 2));
  totalG = totalG + green(get(lx - 1, ly - 2));
  totalG = totalG + green(get(lx, ly - 2));
  totalG = totalG + green(get(lx + 1, ly - 2));
  totalG = totalG + green(get(lx + 2, ly - 2));
  totalG = totalG + green(get(lx + 3, ly - 2));
  totalG = totalG + green(get(lx + 4, ly - 2));
  totalG = totalG + green(get(lx - 3, ly - 1));
  totalG = totalG + green(get(lx - 2, ly - 1));
  totalG = totalG + green(get(lx - 1, ly - 1));
  totalG = totalG + green(get(lx, ly - 1));
  totalG = totalG + green(get(lx + 1, ly - 1));
  totalG = totalG + green(get(lx + 2, ly - 1));
  totalG = totalG + green(get(lx + 3, ly - 1));
  totalG = totalG + green(get(lx + 4, ly - 1));
  totalG = totalG + green(get(lx - 1, ly));
  totalG = totalG + green(get(lx, ly));
  totalG = totalG + green(get(lx + 1, ly));
  totalG = totalG + green(get(lx + 2, ly));
  totalG = totalG + green(get(lx + 3, ly));
  totalG = totalG + green(get(lx + 4, ly));
  totalG = totalG + green(get(lx, ly + 1));
  totalG = totalG + green(get(lx + 1, ly + 1));
  totalG = totalG + green(get(lx + 2, ly + 1));
  totalG = totalG + green(get(lx + 3, ly + 1));
  totalG = totalG + green(get(lx + 4, ly + 1));
  totalG = totalG + green(get(lx, ly + 2));
  totalG = totalG + green(get(lx + 1, ly + 2));
  totalG = totalG + green(get(lx + 2, ly + 2));
  totalG = totalG + green(get(lx + 3, ly + 2));
  totalG = totalG + green(get(lx + 4, ly + 2));
  totalG = totalG + green(get(lx, ly + 3));
  totalG = totalG + green(get(lx + 1, ly + 3));
  totalG = totalG + green(get(lx + 2, ly + 3));
  totalG = totalG + green(get(lx + 3, ly + 3));
  totalG = totalG + green(get(lx + 4, ly + 3));
  totalG = totalG + green(get(lx, ly + 4));
  totalG = totalG + green(get(lx + 1, ly + 4));
  totalG = totalG + green(get(lx + 2, ly + 4));
  totalG = totalG + green(get(lx + 3, ly + 4));
  totalG = totalG + green(get(lx + 4, ly + 4));
  totalG = totalG + green(get(lx, ly + 5));
  totalG = totalG + green(get(lx + 1, ly + 5));
  totalG = totalG + green(get(lx + 2, ly + 5));
  totalG = totalG + green(get(lx + 3, ly + 5));
  totalG = totalG + green(get(lx + 4, ly + 5));
  totalG = totalG + green(get(lx + 1, ly + 6));
  totalG = totalG + green(get(lx + 2, ly + 6));
  totalG = totalG + green(get(lx + 3, ly + 6));
  totalG = totalG + green(get(lx + 4, ly + 6));
  totalG = totalG + green(get(lx + 3, ly + 7));
  totalG = totalG + green(get(lx + 4, ly + 7));
  avgG = totalG / 74;

  totalB = blue(get(lx - 4, ly - 6));
  totalB = totalB + blue(get(lx - 3, ly - 6));
  totalB = totalB + blue(get(lx - 4, ly - 5));
  totalB = totalB + blue(get(lx - 3, ly - 5));
  totalB = totalB + blue(get(lx - 2, ly - 5));
  totalB = totalB + blue(get(lx - 1, ly - 5));
  totalB = totalB + blue(get(lx - 4, ly - 4));
  totalB = totalB + blue(get(lx - 3, ly - 4));
  totalB = totalB + blue(get(lx - 2, ly - 4));
  totalB = totalB + blue(get(lx - 1, ly - 4));
  totalB = totalB + blue(get(lx, ly - 4));
  totalB = totalB + blue(get(lx + 1, ly - 4));
  totalB = totalB + blue(get(lx - 4, ly - 3));
  totalB = totalB + blue(get(lx - 3, ly - 3));
  totalB = totalB + blue(get(lx - 2, ly - 3));
  totalB = totalB + blue(get(lx - 1, ly - 3));
  totalB = totalB + blue(get(lx, ly - 3));
  totalB = totalB + blue(get(lx + 1, ly - 3));
  totalB = totalB + blue(get(lx + 2, ly - 3));
  totalB = totalB + blue(get(lx + 3, ly - 3));
  totalB = totalB + blue(get(lx - 4, ly - 2));
  totalB = totalB + blue(get(lx - 3, ly - 2));
  totalB = totalB + blue(get(lx - 2, ly - 2));
  totalB = totalB + blue(get(lx - 1, ly - 2));
  totalB = totalB + blue(get(lx, ly - 2));
  totalB = totalB + blue(get(lx + 1, ly - 2));
  totalB = totalB + blue(get(lx + 2, ly - 2));
  totalB = totalB + blue(get(lx + 3, ly - 2));
  totalB = totalB + blue(get(lx + 4, ly - 2));
  totalB = totalB + blue(get(lx - 3, ly - 1));
  totalB = totalB + blue(get(lx - 2, ly - 1));
  totalB = totalB + blue(get(lx - 1, ly - 1));
  totalB = totalB + blue(get(lx, ly - 1));
  totalB = totalB + blue(get(lx + 1, ly - 1));
  totalB = totalB + blue(get(lx + 2, ly - 1));
  totalB = totalB + blue(get(lx + 3, ly - 1));
  totalB = totalB + blue(get(lx + 4, ly - 1));
  totalB = totalB + blue(get(lx - 1, ly));
  totalB = totalB + blue(get(lx, ly));
  totalB = totalB + blue(get(lx + 1, ly));
  totalB = totalB + blue(get(lx + 2, ly));
  totalB = totalB + blue(get(lx + 3, ly));
  totalB = totalB + blue(get(lx + 4, ly));
  totalB = totalB + blue(get(lx, ly + 1));
  totalB = totalB + blue(get(lx + 1, ly + 1));
  totalB = totalB + blue(get(lx + 2, ly + 1));
  totalB = totalB + blue(get(lx + 3, ly + 1));
  totalB = totalB + blue(get(lx + 4, ly + 1));
  totalB = totalB + blue(get(lx, ly + 2));
  totalB = totalB + blue(get(lx + 1, ly + 2));
  totalB = totalB + blue(get(lx + 2, ly + 2));
  totalB = totalB + blue(get(lx + 3, ly + 2));
  totalB = totalB + blue(get(lx + 4, ly + 2));
  totalB = totalB + blue(get(lx, ly + 3));
  totalB = totalB + blue(get(lx + 1, ly + 3));
  totalB = totalB + blue(get(lx + 2, ly + 3));
  totalB = totalB + blue(get(lx + 3, ly + 3));
  totalB = totalB + blue(get(lx + 4, ly + 3));
  totalB = totalB + blue(get(lx, ly + 4));
  totalB = totalB + blue(get(lx + 1, ly + 4));
  totalB = totalB + blue(get(lx + 2, ly + 4));
  totalB = totalB + blue(get(lx + 3, ly + 4));
  totalB = totalB + blue(get(lx + 4, ly + 4));
  totalB = totalB + blue(get(lx, ly + 5));
  totalB = totalB + blue(get(lx + 1, ly + 5));
  totalB = totalB + blue(get(lx + 2, ly + 5));
  totalB = totalB + blue(get(lx + 3, ly + 5));
  totalB = totalB + blue(get(lx + 4, ly + 5));
  totalB = totalB + blue(get(lx + 1, ly + 6));
  totalB = totalB + blue(get(lx + 2, ly + 6));
  totalB = totalB + blue(get(lx + 3, ly + 6));
  totalB = totalB + blue(get(lx + 4, ly + 6));
  totalB = totalB + blue(get(lx + 3, ly + 7));
  totalB = totalB + blue(get(lx + 4, ly + 7));
  avgB = totalB / 74;
  return color(avgR, avgG, avgB);
  }
  
   private color getRightColor() {
    float totalR, avgR, totalG, avgG, totalB, avgB;
  totalR = red(get(rx + 4, ry - 6));
  totalR = totalR + red(get(rx + 3, ry - 6));
  totalR = totalR + red(get(rx + 4, ry - 5));
  totalR = totalR + red(get(rx + 3, ry - 5));
  totalR = totalR + red(get(rx + 2, ry - 5));
  totalR = totalR + red(get(rx + 1, ry - 5));
  totalR = totalR + red(get(rx + 4, ry - 4));
  totalR = totalR + red(get(rx + 3, ry - 4));
  totalR = totalR + red(get(rx + 2, ry - 4));
  totalR = totalR + red(get(rx + 1, ry - 4));
  totalR = totalR + red(get(rx, ry - 4));
  totalR = totalR + red(get(rx - 1, ry - 4));
  totalR = totalR + red(get(rx + 4, ry - 3));
  totalR = totalR + red(get(rx + 3, ry - 3));
  totalR = totalR + red(get(rx + 2, ry - 3));
  totalR = totalR + red(get(rx + 1, ry - 3));
  totalR = totalR + red(get(rx, ry - 3));
  totalR = totalR + red(get(rx - 1, ry - 3));
  totalR = totalR + red(get(rx - 2, ry - 3));
  totalR = totalR + red(get(rx - 3, ry - 3));
  totalR = totalR + red(get(rx + 4, ry - 2));
  totalR = totalR + red(get(rx + 3, ry - 2));
  totalR = totalR + red(get(rx + 2, ry - 2));
  totalR = totalR + red(get(rx + 1, ry - 2));
  totalR = totalR + red(get(rx, ry - 2));
  totalR = totalR + red(get(rx - 1, ry - 2));
  totalR = totalR + red(get(rx - 2, ry - 2));
  totalR = totalR + red(get(rx - 3, ry - 2));
  totalR = totalR + red(get(rx - 4, ry - 2));
  totalR = totalR + red(get(rx + 3, ry - 1));
  totalR = totalR + red(get(rx + 2, ry - 1));
  totalR = totalR + red(get(rx + 1, ry - 1));
  totalR = totalR + red(get(rx, ry - 1));
  totalR = totalR + red(get(rx - 1, ry - 1));
  totalR = totalR + red(get(rx - 2, ry - 1));
  totalR = totalR + red(get(rx - 3, ry - 1));
  totalR = totalR + red(get(rx - 4, ry - 1));
  totalR = totalR + red(get(rx + 1, ry));
  totalR = totalR + red(get(rx, ry));
  totalR = totalR + red(get(rx - 1, ry));
  totalR = totalR + red(get(rx - 2, ry));
  totalR = totalR + red(get(rx - 3, ry));
  totalR = totalR + red(get(rx - 4, ry));
  totalR = totalR + red(get(rx, ry + 1));
  totalR = totalR + red(get(rx - 1, ry + 1));
  totalR = totalR + red(get(rx - 2, ry + 1));
  totalR = totalR + red(get(rx - 3, ry + 1));
  totalR = totalR + red(get(rx - 4, ry + 1));
  totalR = totalR + red(get(rx, ry + 2));
  totalR = totalR + red(get(rx - 1, ry + 2));
  totalR = totalR + red(get(rx - 2, ry + 2));
  totalR = totalR + red(get(rx - 3, ry + 2));
  totalR = totalR + red(get(rx - 4, ry + 2));
  totalR = totalR + red(get(rx, ry + 3));
  totalR = totalR + red(get(rx - 1, ry + 3));
  totalR = totalR + red(get(rx - 2, ry + 3));
  totalR = totalR + red(get(rx - 3, ry + 3));
  totalR = totalR + red(get(rx - 4, ry + 3));
  totalR = totalR + red(get(rx, ry + 4));
  totalR = totalR + red(get(rx - 1, ry + 4));
  totalR = totalR + red(get(rx - 2, ry + 4));
  totalR = totalR + red(get(rx - 3, ry + 4));
  totalR = totalR + red(get(rx - 4, ry + 4));
  totalR = totalR + red(get(rx, ry + 5));
  totalR = totalR + red(get(rx - 1, ry + 5));
  totalR = totalR + red(get(rx - 2, ry + 5));
  totalR = totalR + red(get(rx - 3, ry + 5));
  totalR = totalR + red(get(rx - 4, ry + 5));
  totalR = totalR + red(get(rx - 1, ry + 6));
  totalR = totalR + red(get(rx - 2, ry + 6));
  totalR = totalR + red(get(rx - 3, ry + 6));
  totalR = totalR + red(get(rx - 4, ry + 6));
  totalR = totalR + red(get(rx - 3, ry + 7));
  totalR = totalR + red(get(rx - 4, ry + 7));
  avgR = totalR / 74;  


  totalG = green(get(rx + 4, ry - 6));
  totalG = totalG + green(get(rx + 3, ry - 6));
  totalG = totalG + green(get(rx + 4, ry - 5));
  totalG = totalG + green(get(rx + 3, ry - 5));
  totalG = totalG + green(get(rx + 2, ry - 5));
  totalG = totalG + green(get(rx + 1, ry - 5));
  totalG = totalG + green(get(rx + 4, ry - 4));
  totalG = totalG + green(get(rx + 3, ry - 4));
  totalG = totalG + green(get(rx + 2, ry - 4));
  totalG = totalG + green(get(rx + 1, ry - 4));
  totalG = totalG + green(get(rx, ry - 4));
  totalG = totalG + green(get(rx - 1, ry - 4));
  totalG = totalG + green(get(rx + 4, ry - 3));
  totalG = totalG + green(get(rx + 3, ry - 3));
  totalG = totalG + green(get(rx + 2, ry - 3));
  totalG = totalG + green(get(rx + 1, ry - 3));
  totalG = totalG + green(get(rx, ry - 3));
  totalG = totalG + green(get(rx - 1, ry - 3));
  totalG = totalG + green(get(rx - 2, ry - 3));
  totalG = totalG + green(get(rx - 3, ry - 3));
  totalG = totalG + green(get(rx + 4, ry - 2));
  totalG = totalG + green(get(rx + 3, ry - 2));
  totalG = totalG + green(get(rx + 2, ry - 2));
  totalG = totalG + green(get(rx + 1, ry - 2));
  totalG = totalG + green(get(rx, ry - 2));
  totalG = totalG + green(get(rx - 1, ry - 2));
  totalG = totalG + green(get(rx - 2, ry - 2));
  totalG = totalG + green(get(rx - 3, ry - 2));
  totalG = totalG + green(get(rx - 4, ry - 2));
  totalG = totalG + green(get(rx + 3, ry - 1));
  totalG = totalG + green(get(rx + 2, ry - 1));
  totalG = totalG + green(get(rx + 1, ry - 1));
  totalG = totalG + green(get(rx, ry - 1));
  totalG = totalG + green(get(rx - 1, ry - 1));
  totalG = totalG + green(get(rx - 2, ry - 1));
  totalG = totalG + green(get(rx - 3, ry - 1));
  totalG = totalG + green(get(rx - 4, ry - 1));
  totalG = totalG + green(get(rx + 1, ry));
  totalG = totalG + green(get(rx, ry));
  totalG = totalG + green(get(rx - 1, ry));
  totalG = totalG + green(get(rx - 2, ry));
  totalG = totalG + green(get(rx - 3, ry));
  totalG = totalG + green(get(rx - 4, ry));
  totalG = totalG + green(get(rx, ry + 1));
  totalG = totalG + green(get(rx - 1, ry + 1));
  totalG = totalG + green(get(rx - 2, ry + 1));
  totalG = totalG + green(get(rx - 3, ry + 1));
  totalG = totalG + green(get(rx - 4, ry + 1));
  totalG = totalG + green(get(rx, ry + 2));
  totalG = totalG + green(get(rx - 1, ry + 2));
  totalG = totalG + green(get(rx - 2, ry + 2));
  totalG = totalG + green(get(rx - 3, ry + 2));
  totalG = totalG + green(get(rx - 4, ry + 2));
  totalG = totalG + green(get(rx, ry + 3));
  totalG = totalG + green(get(rx - 1, ry + 3));
  totalG = totalG + green(get(rx - 2, ry + 3));
  totalG = totalG + green(get(rx - 3, ry + 3));
  totalG = totalG + green(get(rx - 4, ry + 3));
  totalG = totalG + green(get(rx, ry + 4));
  totalG = totalG + green(get(rx - 1, ry + 4));
  totalG = totalG + green(get(rx - 2, ry + 4));
  totalG = totalG + green(get(rx - 3, ry + 4));
  totalG = totalG + green(get(rx - 4, ry + 4));
  totalG = totalG + green(get(rx, ry + 5));
  totalG = totalG + green(get(rx - 1, ry + 5));
  totalG = totalG + green(get(rx - 2, ry + 5));
  totalG = totalG + green(get(rx - 3, ry + 5));
  totalG = totalG + green(get(rx - 4, ry + 5));
  totalG = totalG + green(get(rx - 1, ry + 6));
  totalG = totalG + green(get(rx - 2, ry + 6));
  totalG = totalG + green(get(rx - 3, ry + 6));
  totalG = totalG + green(get(rx - 4, ry + 6));
  totalG = totalG + green(get(rx - 3, ry + 7));
  totalG = totalG + green(get(rx - 4, ry + 7));
  avgG = totalG / 74;  


  totalB = blue(get(rx + 4, ry - 6));
  totalB = totalB + blue(get(rx + 3, ry - 6));
  totalB = totalB + blue(get(rx + 4, ry - 5));
  totalB = totalB + blue(get(rx + 3, ry - 5));
  totalB = totalB + blue(get(rx + 2, ry - 5));
  totalB = totalB + blue(get(rx + 1, ry - 5));
  totalB = totalB + blue(get(rx + 4, ry - 4));
  totalB = totalB + blue(get(rx + 3, ry - 4));
  totalB = totalB + blue(get(rx + 2, ry - 4));
  totalB = totalB + blue(get(rx + 1, ry - 4));
  totalB = totalB + blue(get(rx, ry - 4));
  totalB = totalB + blue(get(rx - 1, ry - 4));
  totalB = totalB + blue(get(rx + 4, ry - 3));
  totalB = totalB + blue(get(rx + 3, ry - 3));
  totalB = totalB + blue(get(rx + 2, ry - 3));
  totalB = totalB + blue(get(rx + 1, ry - 3));
  totalB = totalB + blue(get(rx, ry - 3));
  totalB = totalB + blue(get(rx - 1, ry - 3));
  totalB = totalB + blue(get(rx - 2, ry - 3));
  totalB = totalB + blue(get(rx - 3, ry - 3));
  totalB = totalB + blue(get(rx + 4, ry - 2));
  totalB = totalB + blue(get(rx + 3, ry - 2));
  totalB = totalB + blue(get(rx + 2, ry - 2));
  totalB = totalB + blue(get(rx + 1, ry - 2));
  totalB = totalB + blue(get(rx, ry - 2));
  totalB = totalB + blue(get(rx - 1, ry - 2));
  totalB = totalB + blue(get(rx - 2, ry - 2));
  totalB = totalB + blue(get(rx - 3, ry - 2));
  totalB = totalB + blue(get(rx - 4, ry - 2));
  totalB = totalB + blue(get(rx + 3, ry - 1));
  totalB = totalB + blue(get(rx + 2, ry - 1));
  totalB = totalB + blue(get(rx + 1, ry - 1));
  totalB = totalB + blue(get(rx, ry - 1));
  totalB = totalB + blue(get(rx - 1, ry - 1));
  totalB = totalB + blue(get(rx - 2, ry - 1));
  totalB = totalB + blue(get(rx - 3, ry - 1));
  totalB = totalB + blue(get(rx - 4, ry - 1));
  totalB = totalB + blue(get(rx + 1, ry));
  totalB = totalB + blue(get(rx, ry));
  totalB = totalB + blue(get(rx - 1, ry));
  totalB = totalB + blue(get(rx - 2, ry));
  totalB = totalB + blue(get(rx - 3, ry));
  totalB = totalB + blue(get(rx - 4, ry));
  totalB = totalB + blue(get(rx, ry + 1));
  totalB = totalB + blue(get(rx - 1, ry + 1));
  totalB = totalB + blue(get(rx - 2, ry + 1));
  totalB = totalB + blue(get(rx - 3, ry + 1));
  totalB = totalB + blue(get(rx - 4, ry + 1));
  totalB = totalB + blue(get(rx, ry + 2));
  totalB = totalB + blue(get(rx - 1, ry + 2));
  totalB = totalB + blue(get(rx - 2, ry + 2));
  totalB = totalB + blue(get(rx - 3, ry + 2));
  totalB = totalB + blue(get(rx - 4, ry + 2));
  totalB = totalB + blue(get(rx, ry + 3));
  totalB = totalB + blue(get(rx - 1, ry + 3));
  totalB = totalB + blue(get(rx - 2, ry + 3));
  totalB = totalB + blue(get(rx - 3, ry + 3));
  totalB = totalB + blue(get(rx - 4, ry + 3));
  totalB = totalB + blue(get(rx, ry + 4));
  totalB = totalB + blue(get(rx - 1, ry + 4));
  totalB = totalB + blue(get(rx - 2, ry + 4));
  totalB = totalB + blue(get(rx - 3, ry + 4));
  totalB = totalB + blue(get(rx - 4, ry + 4));
  totalB = totalB + blue(get(rx, ry + 5));
  totalB = totalB + blue(get(rx - 1, ry + 5));
  totalB = totalB + blue(get(rx - 2, ry + 5));
  totalB = totalB + blue(get(rx - 3, ry + 5));
  totalB = totalB + blue(get(rx - 4, ry + 5));
  totalB = totalB + blue(get(rx - 1, ry + 6));
  totalB = totalB + blue(get(rx - 2, ry + 6));
  totalB = totalB + blue(get(rx - 3, ry + 6));
  totalB = totalB + blue(get(rx - 4, ry + 6));
  totalB = totalB + blue(get(rx - 3, ry + 7));
  totalB = totalB + blue(get(rx - 4, ry + 7));
  avgB = totalB / 74;  
    return color(avgR, avgG, avgB);
  }

 private void displayTop() {
//   ellipse(tx, ty, 13, 13);
//beginShape();
//vertex(tx, ty);
//vertex(tx+5, ty+5);
//vertex(tx, ty+10);
//vertex(tx-5, ty+5);
//endShape(CLOSE);
    beginShape();
    vertex(tx, ty);
    vertex(tx + 4, ty - 2);
    vertex(tx + 8, ty);
    vertex(tx, ty + 4);
    vertex(tx - 8, ty);
    vertex(tx - 4, ty - 2);
    endShape(CLOSE);
  }
  
  private void displayLeft() {
//   ellipse(lx, ly, 13, 13);
//beginShape();
//vertex(lx, ly);
//vertex(lx+5, ly+5);
//vertex(lx, ly+10);
//vertex(lx-5, ly+5);
//endShape(CLOSE);
    beginShape();
    vertex(lx, ly);
    vertex(lx - 4, ly - 2);
    vertex(lx - 4, ly - 6);
    vertex(lx + 4, ly - 2);
    vertex(lx + 4, ly + 7);
    vertex(lx, ly + 5);
    endShape(CLOSE);
  }
  
  private void displayRight() {
//   ellipse(rx, ry, 13, 13);
//beginShape();
//vertex(rx, ry);
//vertex(rx+5, ry+5);
//vertex(rx, ry+10);
//vertex(rx-5, ry+5);
//endShape(CLOSE);
    beginShape();
    vertex(rx, ry);
    vertex(rx + 4, ry - 2);
    vertex(rx + 4, ry - 7);
    vertex(rx - 4, ry - 2);
    vertex(rx - 4, ry + 7);
    vertex(rx, ry + 5);
    endShape(CLOSE);
  }
}
